server:
  port: 8080
  routers:
    - prefix: /api
      middlewares:
        - type: dump-to-log
        - type: request-header
          config:
            hello: world
        - type: response-header
          config:
            Access-Control-Allow-Origin: "*"
      handlers:
        - path: /ip
          type: reverse-proxy
          config: 
            target: "https://api.ipify.org?format=json"
            pathBase: /api/ip